order_app/item/urls.py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'api/items', views.ItemAPIView)

urlpatterns = [
    path('', views.ItemListView.as_view(), name='items'),
    path('create/', views.ItemCreateView.as_view(), name='item_create'),
]

order_app/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from order_app.order.views import OrdersAPIView
from order_app.item.views import ItemAPIView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


router = DefaultRouter()
router.register(r'api/orders', OrdersAPIView)
router.register(r'api/items', ItemAPIView)

schema_view = get_schema_view(
    openapi.Info(title="API Documentation", default_version="v1"),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger-doc"),
    path('orders/', include('order_app.order.urls')),
    path('items/', include('order_app.item.urls')),
]

urlpatterns += [
    path('', include(router.urls))
]

order_app/item/models.py
from django.db import models


class Item(models.Model):
    """
    Модель для позиций, которые будут добавляться в заказ.
    """

    name = models.CharField(unique=True, verbose_name='item_name')
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'item'
        verbose_name = 'item'

    def __str__(self):
        return self.name

order_app/item/forms.py
from django.forms import ModelForm
from .models import Item


class ItemCreateForm(ModelForm):
    """
    Форма для создания новой позиции (item).
    """

    class Meta:
        model = Item
        fields = ['name', 'price']

order_app/item/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.contrib.messages.views import SuccessMessageMixin
from rest_framework.viewsets import ModelViewSet
from .models import Item
from .serializers import ItemSerializer
from .forms import ItemCreateForm


class ItemAPIView(ModelViewSet):
    """
    API ViewSet для работы с позициями, которые можно добавить в заказ.
    Поддерживает стандартные CRUD-операции.
    """
    queryset = Item.objects.all()
    serializer_class = ItemSerializer


class ItemListView(ListView):
    """
    View для отображения списка позиций.
    """
    queryset = Item.objects.all()
    template_name = 'item/items.html'


class ItemCreateView(SuccessMessageMixin, CreateView):
    """
    View для создания новой позиции.
    Обрабатывает форму создания позиции.
    """
    model = Item
    template_name = 'item/item_create.html'
    form_class = ItemCreateForm
    success_url = reverse_lazy('items')
    success_message = 'Item has been added'

order_app/item/templates/item/item_create.html
<h1>Добавить блюдо</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>

order_app/item/templates/item/items.html
{% if messages %}
<ul>
    {% for message in messages %}
    <li> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}

<br>
<div>
    <a role="button" href="{% url 'item_create' %}">Create a new item</a>
</div>
<br>
<hr>
<div>
    <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>PRICE</th>
          </tr>
        </thead>
        <tbody>
          {% for item in item_list %}
          <tr>
            <th scope="row">{{ item.id }}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.price }}</td>
          {% endfor %}
        </tbody>
      </table>
</div>